services:
  - type: web
    name: aetherdrive-backend
    runtime: node
    rootDir: server
    buildCommand: if [ -d "server" ]; then cd server; fi && npm install && node prisma/switch-to-postgres.js && npx prisma generate && npm run build
    startCommand: if [ -d "server" ]; then cd server; fi && node dist/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
